cofide/cofidectl

internal/pkg/kube/exec.go
If using cofidectl with an older (pre 1.31.0) k8s cluster, it may fail
to exec into the spire-server container. This is because websockets are
behind a default false feature gate until 1.31.0, and unsupported before
1.29.0.
This change fixes the issue using a fallback executor, adapted from the
exec code in kubectl. It will try to use websockets, then fall back to
SPDY if unavailable.
Fixes: #3
=> Fall back to SPDY for exec if WebSockets aren't supported

README.md
=> Fix CI status badge in README.md (again...)

internal/pkg/spire/spire.go, internal/pkg/workload/workload.go
Previously they were displayed as:
trust_domain:"td1" path:"/ns/ns3/sa/default"
Now they are displayed as a URL:
spiffe://td1/ns/ns3/sa/default
=> Fix formatting of workload IDs in workload list command

internal/pkg/provider/helm/values.go, internal/pkg/provider/helm/values_test.go
Federation is now only enabled when a trust zone has a federation
relationship with another trust zone.
Fixes: #26
=> Disable federation by default

.github/workflows/ci.yml
Rename the step to Run golangci-lint so it is more clear when it fails that it isn't just the install that failed.
=> Raname golangci-lint name

cmd/cofidectl/cmd/up.go
After #27 merged we started seeing failures in the federation
integration test:
cofidectl workload discover
Error: failed to stream exec: Internal error occurred: unable to upgrade connection: container not found ("spire-server")
error: Recipe `integration-test` failed on line 20 with exit code 1
In #27 the Helm configuration was changed to only enable federation in
SPIRE server when there is a federation relationship that has a bundle
endpoint available. On the initial Helm install this would not be the
case, so federation would be disabled. On the post-install configure
Helm install, we would have bundle endpoints and so federation would be
enabled and SPIRE server would be restarted. This caused any commands
running immediately after cofidectl up that rely on SPIRE server being
up (in …
=> Wait for SPIRE server pod & service after post-install config

tests/integration/federation/test.sh, tests/integration/single-trust-zone/test.sh
wait_for_pong needs to return 1 when retries are exhausted in order to
signal failure.
The kubectl wait exit code was being ignored because wait_for_pong is
called as an if conditional. Pull it out of wait_for_pong. Some context
on the issue:
https://stratus3d.com/blog/2019/11/29/bash-errexit-inconsistency/
=> Fix wait_for_pong in integration tests

go.mod, go.sum, pkg/plugin/grpc.go, pkg/plugin/plugin.go
Implements all data source gRPC service RPCs for the client and service.
Adds a type check to ensure that the client implements the DataSource
interface.
Fixes: #59
Depends-On: https://github.com/cofide/cofide-api-sdk/pull/9
=> Implement full data source gRPC client and service

cmd/cofidectl/main.go, pkg/cmd/context/context.go, pkg/plugin/plugin_test.go
- **Add unit test for IsDataSourceServeCmd**
- **Move signal handling to command context**
=> Move signal handling to command context

cmd/cofidectl/cmd/trustzone/helm/helm.go, cmd/cofidectl/cmd/up.go, internal/pkg/attestationpolicy/attestationpolicy.go, pkg/provider/helm/values.go, pkg/provider/helm/values_test.go
- This PR updates the existing `HelmValuesGenerator` [GenerateValues](https://github.com/cofide/cofidectl/blob/b0ac6d298b9468d6b3189e12c1828abbb3530cf6/pkg/provider/helm/values.go#L31) method to support merging in a set of values from an additional source, beyond user supplied values (as added in #5), as required by #57.
- This PR decomposes the `GenerateValues` method, uses native Go types with a merge function (instead of CUE) and adds additional test coverage.
=> feat: Update `GenerateValues` method to support provisioning plugin values injection

internal/pkg/attestationpolicy/attestationpolicy.go, pkg/provider/helm/values_test.go
After #62 merged we started seeing some warnings during cofidectl up.
This is due to a change in the type of the Helm values generated for
matchLabels in clusterSPIFFEIDs from map[string]any to
map[string]string.
This change reverts to map[string]any, which removes the warning.
Fixes: #65
=> Fix Helm warnings seen in cofidectl up

cmd/cofidectl/cmd/trustzone/helm/helm.go, internal/pkg/attestationpolicy/attestationpolicy.go, internal/pkg/federation/federation.go, internal/pkg/test/fixtures/fixtures.go, internal/pkg/trustprovider/trustprovider.go, pkg/plugin/provision/spirehelm/spirehelm.go, pkg/provider/helm/helm.go, pkg/provider/helm/helm_test.go, pkg/spire/spire.go
As part of changes introduced with #57, this PR is a follow up to replace instances of `map[string]interface{}` to use the `any` alias, as proposed [here](https://github.com/cofide/cofidectl/pull/62#discussion_r1870020000).
=> feat: Replace instances of `map[string]interface{}` to use the `any` alias

cmd/cofidectl/cmd/down.go, cmd/cofidectl/cmd/statusspinner/statusspinner.go, cmd/cofidectl/cmd/up.go, tests/integration/single-trust-zone/test.sh
(implements https://github.com/cofide/cofidectl/issues/67)
* Adds `--quiet` opt to `up` command, which switches off the cursor animation
* Adds `quiet bool` to `WatchProvisionStatus` to conditional the `spinner.Start()` invocation per event. The quiet true case simply doesn't start the spinner
* Concretely sets `down` to false (these logs are less verbose, and we don't encounter `cofidectl down` as much in CI)
* `single-trust-zone` test now uses `./cofidectl up --quiet` (perhaps a better place for this, a new test?)
=> Adding --quiet mode

pkg/provider/helm/values.go, pkg/provider/helm/values_test.go
If you create a trust zone with no attestation policies bound to it, we
previously enabled the default clusterSPIFFEID. This resource matches
any pod in a non-spire namespace.
This behaviour is surprising, and we should instead rely on an explicit
catch-all attestation policy being bound to the trust zone:
cofidectl attestation-policy add kubernetes --name catch-all
This commit fixes the issue by disabling the default clusterSPIFFEID.
Fixes: #92
=> Disable the default clusterSPIFFEID

cmd/cofidectl/cmd/workload/workload.go, internal/pkg/trustprovider/trustprovider.go, internal/pkg/workload/workload.go, pkg/provider/helm/values_test.go
`cofidectl workload status foo --pod-name foo-pod --namespace bar --trust-zone foo`
Initially, this command will take a workload name, with pod name, namespace and trust-zone as flags, and use Maartje's "attest-me" implementation via a debug container to return human-readable cert information with the CLI.
As a follow-up, I'd like to make it simpler to reference the workload (ideally a single argument) and for pod and cluster info be inferred, but that'll depend on how we handle 'workloads' and will need some additional thought.
=> Adds a workload status command 

internal/pkg/workload/workload.go
- This PR updates the `cofidectl-debug-container/cmd` image reference to use the updated `cofidectl-debug-container` name, as required by #107.
=> feat: Update reference to the `cofidectl-debug-container` image name

go.mod, go.sum
- This PR bumps the version of `golang.org/x/net` to `v0.33.0` to address this [Dependabot](https://github.com/cofide/cofidectl/security/dependabot/2) alert (which couldn't be automatically resolved).
=> fix: Bump `golang.org/x/net` to v0.33.0

.github/workflows/ci.yml, .golangci.yaml
- This PR adds a small fix to the `goheader` linter setting in `.golangci.yaml` to allow all years from 2024 and onwards to be valid, resolving the following error:
```
run golangci-lint
Running [/home/runner/golangci-lint-1.63.1-linux-amd64/golangci-lint run  --timeout=5m] in [/home/runner/work/cofidectl/cofidectl] ...
Received 1463000 of 1463000 (100.0%), 1.4 MBs/sec
Error: pkg/plugin/local/local.go:1:14: Expected:2025, Actual: 2024 Cofide Limited. (goheader)
// Copyright 2024 Cofide Limited.
^
Error: pkg/plugin/local/local_test.go:1:14: Expected:2025, Actual: 2024 Cofide Limited. (goheader)
// Copyright 2024 Cofide Limited.
^
Error: internal/pkg/federation/federation.go:1:14: Expected:2025, Actual: 2024 Cofide Limited. (goheader)
// Copyright 2024 Cofide Limited.
^
Error: issues found …
```
=> fix: Update `goheader` linter setting to support 2024 and onwards

tests/integration/federation/test.sh, tests/integration/single-trust-zone/test.sh
- This small PR adds the `cofidectl workload status` command to each of the integration tests as required by #107.
=> feat: `cofidectl workload status` command added to each integration test

cmd/cofidectl/cmd/root.go, cmd/cofidectl/cmd/root_test.go, pkg/cmd/context/context.go, pkg/plugin/manager/manager.go
This allows setting the log level threshold. The default is ERROR.
Currently we do not do much logging in cofidectl, but this may change
now that we can set the level.
The main benefit for now is that gRPC plugin log level is also set based
on this argument, giving more insight into plugin issues.
Fixes: #82
=> Add --log-level argument to root command

cmd/cofidectl/cmd/federation/federation.go, tests/integration/federation/test.sh, tests/integration/single-trust-zone/test.sh
implements https://github.com/cofide/cofidectl/issues/50
* Adds Reason column to `cofidectl federation list` output
* Adds const strings for statuses and reasons
* Adds integration test case for no bundle
=> Adds Reason column to `federation list` output

internal/pkg/config/testdata/config/full.yaml, internal/pkg/test/fixtures/fixtures.go, internal/pkg/trustprovider/trustprovider.go, internal/pkg/workload/workload.go, pkg/provider/helm/helm.go, pkg/provider/helm/values.go, pkg/provider/helm/values_test.go, pkg/spire/spire.go, pkg/spire/spire_server_cli.go, pkg/spire/spire_server_cli_test.go, pkg/spire/spire_test.go, tests/integration/federation/test.sh, tests/integration/lib.sh, tests/integration/single-trust-zone/test.sh
Setting the Helm chart recommendations enabled flag applies various
changes to the configuration, as described in [1]:
- 2 namespace layout (spire-server & spire-system)
- Namespace pod security standards
- Priority class name
- Prometheus
- Strict mode
- Security contexts
We also use a 3rd namespace for the Helm chart state and CRDs as
described in [2].
[1] https://spiffe.io/docs/latest/spire-helm-charts-hardened-about/recommendations/
[2] https://spiffe.io/docs/latest/spire-helm-charts-hardened-about/namespaces/
Fixes: #113
Fixes: #114
=> Enable Helm chart recommendations, use 3-namespace deployment

.github/workflows/ci.yml, .github/workflows/govulncheck.yml, Justfile
- **CI: Run Go tests with race detector enabled**
- **Don't run pull request workflow on labeled/unlabeled events**
=> CI: Enable race detector when running Go tests

cmd/cofidectl-test-plugin/main.go, pkg/plugin/manager/manager.go, pkg/plugin/manager/manager_test.go, pkg/plugin/provision/spirehelm/spireapi.go, pkg/plugin/provision/spirehelm/spirehelm.go, pkg/plugin/provision/spirehelm/spirehelm_test.go
This allows for better unit testing with a fake SPIRE API.
=> Refactor SpireHelm to use a SPIREAPI interface

.github/workflows/release.yml
In the test release for 6.0.1, the workflow failed to upload artifacts: https://github.com/cofide/cofidectl/actions/runs/13201616037/job/36854773746
=> fix: gh release upload path doesn't match build output

cmd/cofidectl/cmd/federation/federation.go, cmd/cofidectl/cmd/trustzone/trustzone.go, cmd/cofidectl/cmd/workload/workload.go, internal/pkg/trustzone/trustzone.go, pkg/plugin/provision/spirehelm/spirehelm.go
This allows for creation of trust zones without an associated cluster.
Fixes: #162
=> feat: Add --no-cluster argument to trust-zone add command

.github/workflows/release.yml
This avoids the race to create a release. This change also brings in
some caching improvements from elsewhere.
=> fix: change pre-release-binaries workflow to a release trigger

go.mod, go.sum, pkg/plugin/datasource/interface.go, pkg/plugin/datasource/plugin.go, pkg/plugin/local/local.go, pkg/plugin/local/local_test.go
This is a first step towards #174, required for building with cofide-api-sdk v0.15.0, but does not use the new method.
=> feat: add ListAPBindings method to DataSource interface and gRPC plugin

cmd/cofidectl/cmd/apbinding/apbinding.go, pkg/plugin/datasource/plugin.go, pkg/provider/helm/values.go, pkg/provider/helm/values_test.go
- **fix: stop accessing bindings & federations in trust zone message**
This change stops accessing the AttestationPolicy and Federations fields
in the TrustZone message outside of the local datasource, instead using
the datasource methods available to access bindings and federations.
This allows datasource implementations to store these resources outside
of the trust zone.
Fixes: #174
- **fix: pass trust zone name to ListFederationsByTrustZone gRPC request**
=> fix: stop accessing bindings & federations in trust zone message

go.mod
Request smuggling due to acceptance of invalid chunked data in net/http
https://pkg.go.dev/vuln/GO-2025-3563
=> fix: bump go to 1.24.2 to fix GO-2025-3563

cmd/cofidectl/cmd/apbinding/apbinding.go, cmd/cofidectl/cmd/attestationpolicy/attestationpolicy.go, cmd/cofidectl/cmd/cluster/cluster.go, cmd/cofidectl/cmd/federation/federation.go, cmd/cofidectl/cmd/trustzone/trustzone.go, cmd/cofidectl/cmd/trustzone/trustzone_test.go, cmd/cofidectl/cmd/workload/workload.go, pkg/plugin/datasource/interface.go, pkg/plugin/datasource/plugin.go, pkg/plugin/local/local.go, pkg/plugin/local/local_test.go, pkg/provider/helm/helm.go, tests/integration/federation/test.sh, tests/integration/lib.sh, tests/integration/single-trust-zone/test.sh
This change adds the following CLI commands:
- attestation-policy del
- cluster del
- federation del
- trust-zone del
They delete the corresponding resource type.
It also adds DataSource interface methods:
- DestroyTrustZone
- DestroyCluster
- DestroyAttestationPolicy
- DestroyFederation
The integration tests have been updated to exercise the new commands.
It also adds support for alternative argument names in the federation
add command, as required by #49.
Fixes: #206
Fixes: #49
=> feat: add CLI commands and data source methods for deletion

pkg/provider/helm/helm.go, tests/integration/single-trust-zone/test.sh
When running cofidectl up, the secrets for the spire and spire-crds Helm
releases were previously installed into the default namespace, rather
than the expected spire-mgmt namespace:
kubectl get secrets -n default
NAMESPACE     NAME                                 TYPE                            DATA   AGE
default       sh.helm.release.v1.spire-crds.v1     helm.sh/release.v1              1      38m
default       sh.helm.release.v1.spire.v1          helm.sh/release.v1              1      38m
This is confusing because the Helm release list command showed the
releases as being in the spire-mgmt namespace:
helm list -A
NAME        	NAMESPACE 	REVISION	UPDATED                                	STATUS  	CHART             	APP VERSION
spire       	spire-mgmt	1       	2025-05-08 09:34:01.860454781 …
=> fix: install Helm secrets into spire-mgmt namespace

cmd/cofidectl/cmd/trustzone/helm/helm.go, go.mod, go.sum, pkg/plugin/provision/interface.go, pkg/plugin/provision/plugin.go, pkg/plugin/provision/plugin_test.go, pkg/plugin/provision/spirehelm/providerfactory.go, pkg/plugin/provision/spirehelm/spirehelm.go, pkg/plugin/provision/spirehelm/spirehelm_test.go, tests/integration/federation/test.sh
This change adds a GetHelmValues method to the Provision interface. This
allows provision plugins to generate their own Helm values for
deployment.
Fixes: #104
=> feat: Add GetHelmValues method to Provision interface

internal/pkg/config/schema.cue, internal/pkg/config/validator_test.go, pkg/plugin/local/local.go, pkg/plugin/local/local_test.go
These changes generate a UUID for local resources. This is the same behaviour as with a remote backend which allows the tooling to transition to ID based resource selection.
Fixes https://github.com/cofide/cofidectl/issues/201
=> Add UUIDs to local resources

cmd/cofidectl/cmd/cluster/cluster.go, cmd/cofidectl/cmd/federation/federation.go, cmd/cofidectl/cmd/trustzone/trustzone.go, cmd/cofidectl/cmd/trustzone/trustzone_test.go, cmd/cofidectl/cmd/workload/workload.go, pkg/provider/helm/helm.go
If a Kubernetes cluster has been deleted, then previously it was not
possible to delete the corresponding cofidectl cluster and trust zone
because the Helm chart installation check would fail.
This change provides a workaround with a --force flag that skips the pre-delete checks.
Fixes: #225
=> fix: add a --force argument to trust zone and cluster delete

pkg/plugin/local/local.go
The addition of two features conflicted and was not caught in CI:
- federation deletion
- resource IDs in the local data source
The addition of resource IDs broke the proto comparison, because the CLI
does not yet understand or use IDs.
This change fixes the issue by comparing the From and To fields
directly.
=> fix: federation deletion with local data source

internal/pkg/trustprovider/trustprovider.go, pkg/provider/helm/helm.go, pkg/provider/helm/helm_test.go, pkg/provider/helm/values.go, pkg/provider/helm/values_test.go, pkg/spire/spire_server_cli.go
- This PR bumps the following Helm charts to their latest versions:
-  `spire`
- `spire-crds`
=> chore: Bump SPIRE Helm chart versions

pkg/provider/helm/values.go, pkg/provider/helm/values_test.go
In a Cofide plugin we override values, including disabling the controller-manager. This PR adds a check to see if the controller-manager is enabled and whether to add the configuration to the values.
=> Check values override for controller-manager config

internal/pkg/config/config.go, internal/pkg/config/config_test.go, internal/pkg/config/schema.cue, internal/pkg/config/testdata/config/full.yaml, internal/pkg/config/testdata/config/missing_trust_zone_field.yaml, internal/pkg/test/fixtures/fixtures.go, pkg/plugin/local/local.go, pkg/plugin/local/local_test.go, pkg/provider/helm/values_test.go
Refactors APBs (attestation policy bindings) and Feds (federations) from being nested in trust zones (deprecated) to top-level config (the new way).
Fixes issue #175.
=> Refactor APBs and Feds to the top level config

pkg/provider/helm/helm.go, tests/integration/single-trust-zone/test.sh
Otherwise we may hit the following issue:
Uninstalling: Failed to uninstall SPIRE CRDs for workload-63d89cf2 in 63d89cf2
Error: spire-crds not installed
=> fix: don't try to uninstall SPIRE CRDs if they were not installed

go.mod
Fixes https://pkg.go.dev/vuln/GO-2025-3849
=> fix: bump go to 1.24.6

cmd/cofidectl/cmd/trustzone/trustzone.go, cmd/cofidectl/cmd/trustzone/trustzone_test.go
This PR improves the error handling in parsing the OIDC issuer URL. The OIDC issuer URL should be served over HTTPS. It  also removes any trailing slashes if present.
=> Parse the OIDC issuer URL and handle errors
